export const projectsData = [
  {
    no: 1,
    description:
      "AMENAM AMKP1-42 P-15 well hookup (electrical instrumentation work)",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2023",
    status: "COMPLETED",
  },
  {
    no: 2,
    description: "OML 100 IME Wells OP2 & 4 hook-up and commissioning",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2022",
    status: "COMPLETED",
  },
  {
    no: 3,
    description:
      "OML 99: Decommissioning of Monorail Electrical Hoists on AMP 1&2 (8Nos)",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2021",
    status: "Ongoing",
  },
  {
    no: 4,
    description:
      "AMENAM AMKP1-43 p-16 well hook-up (electrical instrumentation work)",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2019",
    status: "Ongoing",
  },
  {
    no: 5,
    description:
      "Fabrication of 10Nos oil cath pans for Ubit Offshore Production Platform",
    client: "EESL/CAMERON",
    reference: "Andy Anyanwu",
    // location: "Port Harcourt",
    // dateExecuted: "2018",
    status: "COMPLETED",
  },
  {
    no: 6,
    description:
      "Construction, blast, and paint of ROV Docking Frames - 3Nos for USAN/TOTAL Project",
    client: "CAMERON",
    reference: "Dada Fiakpo",
    // location: "Port Harcourt",
    // dateExecuted: "2018",
    status: "COMPLETED",
  },
  {
    no: 7,
    description: "Instrument works for Well Head temporary adaptation hook-up",
    client: "PEM Offshore/Mobil",
    reference: "Fred Stosky",
    // location: "Port Harcourt",
    // dateExecuted: "2018",
    status: "COMPLETED",
  },
  {
    no: 8,
    description: "OFON CHICK-SAN pipes replacement - E&I Works",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2017",
    status: "COMPLETED",
  },
  {
    no: 9,
    description: "OML 99 AMENAM Kpono Field. Production Output of 100,000BL/D",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2016",
    status: "COMPLETED",
  },
  {
    no: 10,
    description:
      "Replacement of existing 10.0TN Crane on the Weather Deck of Edikan Platform.",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2016",
    status: "COMPLETED",
  },
  {
    no: 11,
    description:
      "Workshop Fabrication of H-Beams & Scaffolding Operation for FSO Unity OWT Facility Upgrade.",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2015",
    status: "COMPLETED",
  },
  {
    no: 12,
    description: "Fabrication & Installation of IBWA Well 14 Flow Line and SDV",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2015",
    status: "COMPLETED",
  },
  {
    no: 13,
    description: "Installation of Fabricated Flow Lines Rack",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Port Harcourt",
    // dateExecuted: "2015",
    status: "COMPLETED",
  },
  {
    no: 14,
    description:
      "Obagi - Ubeta Road Construction Work. Part of TOTAL's Corporate Social Responsibility & Developmental Project to Host Community.",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "Kolu Ama, Offshore Brass",
    // dateExecuted: "2014",
    status: "COMPLETED",
  },
  {
    no: 15,
    description:
      "Rafting, Pilling and Concrete Flooring Work Ongoing at Site for Bonny Telecom Mast Installation",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "NUN RIVERS-SPDC PROJECT",
    // dateExecuted: "2013",
    status: "COMPLETED",
  },
  {
    no: 16,
    description:
      "Site Preparation for Rig Mobilization for Gas Wells Drilling Operation at Obite Site.	",
    client: "TOTAL",
    reference: "Kingsley Anowa",
    // location: "FPSO Oyo field offshore Lagos",
    // dateExecuted: "2013",
    status: "COMPLETED",
  },
];
